### ISSUE TITLE
roadmap to mvp

### ISSUE THREAD

**Issue by petar** [gov4git/gov4git#1]
- [ ] __milestone 1:__ verifiable prioritization polling based on QV _(~2 months)_
  - [ ] build out working prototype _(1 month)_
    - [x] identity management
      - [x] generating new identities with ed25519 signature keys
    - [x] community user and group management
      - [ ] `balance` operation for balance management (badges, voting credits, etc.)
    - [ ] prioritization polling operations
      - [x] `poll` operation (create a poll)
      - [ ] `vote` operation (vote on an open poll)
      - [ ] `tally` operation (collect votes and report aggregates)
      - [ ] `seal` operation (finalize a poll and merge into main branch with a verifiable record)
      - [ ] `list` operation (list open polls)
    - [ ] deployment to a small group of users __(expected in October 2022)__
  - [ ] polish _(1 month)_
    - [ ] evaluation of user experience
      - [ ] installation flow
      - [ ] error messages and corrective suggestions
      - [ ] issue tracking setup and bug reporting automation
    - [ ] versioning and interoperability
      - [ ] add governance protocol version info in git artifacts
    - [ ] documentation
      - [ ] blog article describing end-to-end user workflow and effect of operations on git repos
      - [ ] terminal screencast video demonstrating user workflow
    - [ ] test
      - [ ] testing framework
      - [ ] test coverage (all operations)

- [ ] __milestone 2:__ verifiable PR approval _(1 month)_
  - TBD

- [ ] __milestone 3:__ retro-active community history verification _(1 month)_
  - TBD
