### ISSUE TITLE
milestone 1 (internal deployment)

### ISSUE THREAD

**Issue by petar** [gov4git/gov4git#31]
Milestone 1 includes a baseline set of application features, as well as operational preparedness of the software stack for live deployment to an internal group of users. The product spec for milestone 1 can be found here https://github.com/gov4git/gov4git/blob/main/doc/product-spec-m1.md

## Technical roadmap

Technical tasks for this milestone:

### Backend (command line client) features

- [x] https://github.com/gov4git/gov4git/pull/33
- [x] #51
- [x] #52
- [x] #59
- [x] support for cancelling ballots
- [x] https://github.com/gov4git/gov4git/pull/54
- [x] #56
- [x] #57
- [x] #58
- [x] #65 (enables zero-latency UX)

#### Operational readiness
- [ ] #50
- [x] #41
- [ ] desktop app logs the verbose cli output for troubleshooting purposes
- [ ] #42

#### Features
- [ ] #68
- [ ] #67

### Integration with GitHub

- [x] cli command for importing GitHub issues and request
- [x] GitHub action template for importing from GitHub and sweeping the community votes
- [x] deployment instructions

### Frontend Desktop App

- [ ] decide and freeze terms for "voting credits" vs "impact" (after the square root)
- [ ] UI user stories: https://github.com/gov4git/desktop-application/issues/55
- [ ] screen for tracking user's past votes (with details) and which have been processed?

#### Backend tests

Application correctness tests:
- [x] #45
- [x] #47
- [x] test open ballot, vote, tally, close ballot
- [x] test freeze/unfreeze ballot
- [x] test transfer credits from one account to another

Command-line client interface tests. _These tests ensure that the command-line interface (which is used by the desktop app) behaves as expected. These tests also act as a specification of the cli interface._
- [x] https://github.com/gov4git/gov4git/pull/49
  - [x] test interface of `balance` command
  - [x] test interface of `ballot` command
  - [x] test interface of `group` command
  - [x] test interface of `user` command
  - [x] test interface of `member` command
  - [x] test interface of `init-gov` command
  - [x] test interface of `init-id` command
  
#### Integration with desktop tests:
- [ ] manually test all UI features and flows (installation, creating identity, etc)
- [ ] manually verify desktop app does not freeze while communicating with backend

#### Integration with GitHub tests:
- [x] test that each GitHub action invokes the cli correctly (Trigger GitHub Action locally. Use cli to check for expected result.)

## Business roadmap

- [ ] project website on GitHub pages
- [ ] project blog on GitHub pages (to post articles on features, collaborations, etc)

**Comment by jason-entenmann** [comment]
Product (Gov4git side)

- [ ] Compatibility with a multitude of languages.

Is this something we want to take on with our current timeline constraints? How will the lack of this compatibility effect the user experience in a non-English language?

**Comment by pluralitybook** [comment]
This is only for back-end, correct?  All the design is being handled through the other conversation?  We need a way to designate a planned resolution date for PRs, which is not currently an affordance of GitHub I am aware of.

**Comment by pluralitybook** [comment]
For clarification: voters should be able to add or remove votes and to see the current aggregate vote (via QF) unless issues is frozen.  If frozen they should not be able to add or remove votes, only view total.  Negative votes should be allowed; these are costly but reduce the issue priority rather than augmenting it.
Modulo these, I approve.

**Comment by petar** [comment]
@pluralitybook To be accurate, is this what you have in mind:

Let $p_u^t$ be voting credits user $u$ spends on an upvote at time $t$. Similarly, let $n_u^t$ be the voting credits user $u$ spends on a downvote at time $t$. The priority of the issue being voted on equals:
$$ \sum_u \sqrt \left( \sum_t p_u^t \right) - \sum_u \sqrt \left( \sum_t p_u^t \right)$$

**Comment by petar** [comment]
@dworthen @jason-entenmann I just released https://github.com/gov4git/gov4git/releases/tag/v1.1.5 which includes:
- integration with github issues and pull requests
- automated deployment of governance targeting a github project repository
- deployment and maintenance guide
