### ISSUE TITLE
milestone 2 checklist (public deployment)

### ISSUE THREAD

**Issue by petar** [gov4git/gov4git#35]
Milestone 2 adds mechanisms to the application.

Tasks:
- [ ] https://github.com/gov4git/gov4git/issues/34
- [ ] formal model for the mechanisms
- [ ] implement mechanisms in cli
- [ ] incorporate mechanisms in desktop app
